services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: product_db
    environment:
      SA_PASSWORD: "StrongPass#123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d   # initialization scripts
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P StrongPass#123 -Q 'SELECT 1'"]
      interval: 10s
      retries: 10
      start_period: 20s

  api:
    build:
      context: ./ProductManagement.API
      dockerfile: Dockerfile
    container_name: product_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=ProductDB;User Id=sa;Password=StrongPass#123;TrustServerCertificate=true;"
    ports:
      - "5000:80"
